import { Inter } from "next/font/google";

import { notFound } from "next/navigation";
import { NextIntlClientProvider, useMessages } from "next-intl";

//
import "../../../public/assets/css/bootstrap-icons.css";
import "../../../public/assets/css/boxicons.min.css";
import "../../../public/assets/css/fontawesome.min.css";
import "../../../public/assets/css/bootstrap.min.css";
import "../../../public/assets/css/swiper-bundle.min.css";
import "../../../public/assets/css/nice-select.css";
import "../../../styles/custom.css";
import "../../../public/assets/css/style.css";

import { WhatsAppProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AFAQ Global",
  // description: "Generated by create next app",
};

export default function LocaleLayout({ children, params: { locale } }) {
  const messages = useMessages();

  return (
    <html lang={locale} dir={locale == "ar" ? "rtl" : "ltr"}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <WhatsAppProvider lang={locale}>{children}</WhatsAppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
